name: env

channels:
  - defaults

dependencies:
  - python=3.9
  - pip

  - pip:
    - --find-links https://download.pytorch.org/whl/cpu/torch_stable.html
    - -r requirements.txt
    - -r requirements-cpu.txt