name: docs

on:
  push:
    branches:
      - master

jobs:

  build-docs:
    name: build-docs
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [ubuntu-20.04]
        python-version: [3.9]
        requires: ['latest']
    steps:
      - name: Deploy docs on gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: 'docs/_build/html'
