name: Deploy docs on GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - docs/**

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [ubuntu-20.04]
        python-version: [3.9]
        requires: ['latest']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          publish_branch: gh-pages
          publish_dir: docs/_build/
